version: 2
updates:
  - package-ecosystem: "helm"
    directories: 
      - /charts/*
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependency"
    ignore:
      - dependency-name: "common"
